module test:count:func:one

func somefunc() -> Result<int, _ : Exception> = okResult(0)
